# Generated by Django 4.2.22 on 2025-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('AR', 'Arabic'), ('ZH', 'Chinese')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
            ],
        ),
    ]
