# Generated by Django 5.2.4 on 2025-08-07 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_booking_course_exercise_lesson_delete_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='message',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
