# Generated by Django 5.2.4 on 2025-08-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_rename_notes_booking_message_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
