# Generated by Django 5.2.4 on 2025-08-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_booking_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
    ]
