# Generated by Django 5.2.4 on 2025-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_alter_course_options_remove_course_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student')], default='student', max_length=10),
        ),
    ]
